[package]
name = "no-dpi-socks"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.7"
dns-lookup = "2.0"
env_logger = "0.11"
log = "0.4"

[dependencies.tokio]
version = "1.39"
features = [ "rt", "rt-multi-thread", "net", "io-util", "macros" ]
